(cl:defpackage aruco_service-srv
  (:use )
  (:export
   "GENERATEARUCOTAGS"
   "<GENERATEARUCOTAGS-REQUEST>"
   "GENERATEARUCOTAGS-REQUEST"
   "<GENERATEARUCOTAGS-RESPONSE>"
   "GENERATEARUCOTAGS-RESPONSE"
  ))

