// Generated by gencpp from file aruco_service/GenerateArUcoTagsResponse.msg
// DO NOT EDIT!


#ifndef ARUCO_SERVICE_MESSAGE_GENERATEARUCOTAGSRESPONSE_H
#define ARUCO_SERVICE_MESSAGE_GENERATEARUCOTAGSRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aruco_service
{
template <class ContainerAllocator>
struct GenerateArUcoTagsResponse_
{
  typedef GenerateArUcoTagsResponse_<ContainerAllocator> Type;

  GenerateArUcoTagsResponse_()
    {
    }
  GenerateArUcoTagsResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GenerateArUcoTagsResponse_

typedef ::aruco_service::GenerateArUcoTagsResponse_<std::allocator<void> > GenerateArUcoTagsResponse;

typedef boost::shared_ptr< ::aruco_service::GenerateArUcoTagsResponse > GenerateArUcoTagsResponsePtr;
typedef boost::shared_ptr< ::aruco_service::GenerateArUcoTagsResponse const> GenerateArUcoTagsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace aruco_service

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aruco_service/GenerateArUcoTagsResponse";
  }

  static const char* value(const ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GenerateArUcoTagsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::aruco_service::GenerateArUcoTagsResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // ARUCO_SERVICE_MESSAGE_GENERATEARUCOTAGSRESPONSE_H
