// Generated by gencpp from file aruco_service/GenerateArUcoTags.msg
// DO NOT EDIT!


#ifndef ARUCO_SERVICE_MESSAGE_GENERATEARUCOTAGS_H
#define ARUCO_SERVICE_MESSAGE_GENERATEARUCOTAGS_H

#include <ros/service_traits.h>


#include <aruco_service/GenerateArUcoTagsRequest.h>
#include <aruco_service/GenerateArUcoTagsResponse.h>


namespace aruco_service
{

struct GenerateArUcoTags
{

typedef GenerateArUcoTagsRequest Request;
typedef GenerateArUcoTagsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GenerateArUcoTags
} // namespace aruco_service


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aruco_service::GenerateArUcoTags > {
  static const char* value()
  {
    return "053c309a2f9c891d1b57cd350d17a1e7";
  }

  static const char* value(const ::aruco_service::GenerateArUcoTags&) { return value(); }
};

template<>
struct DataType< ::aruco_service::GenerateArUcoTags > {
  static const char* value()
  {
    return "aruco_service/GenerateArUcoTags";
  }

  static const char* value(const ::aruco_service::GenerateArUcoTags&) { return value(); }
};


// service_traits::MD5Sum< ::aruco_service::GenerateArUcoTagsRequest> should match
// service_traits::MD5Sum< ::aruco_service::GenerateArUcoTags >
template<>
struct MD5Sum< ::aruco_service::GenerateArUcoTagsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aruco_service::GenerateArUcoTags >::value();
  }
  static const char* value(const ::aruco_service::GenerateArUcoTagsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aruco_service::GenerateArUcoTagsRequest> should match
// service_traits::DataType< ::aruco_service::GenerateArUcoTags >
template<>
struct DataType< ::aruco_service::GenerateArUcoTagsRequest>
{
  static const char* value()
  {
    return DataType< ::aruco_service::GenerateArUcoTags >::value();
  }
  static const char* value(const ::aruco_service::GenerateArUcoTagsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aruco_service::GenerateArUcoTagsResponse> should match
// service_traits::MD5Sum< ::aruco_service::GenerateArUcoTags >
template<>
struct MD5Sum< ::aruco_service::GenerateArUcoTagsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aruco_service::GenerateArUcoTags >::value();
  }
  static const char* value(const ::aruco_service::GenerateArUcoTagsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aruco_service::GenerateArUcoTagsResponse> should match
// service_traits::DataType< ::aruco_service::GenerateArUcoTags >
template<>
struct DataType< ::aruco_service::GenerateArUcoTagsResponse>
{
  static const char* value()
  {
    return DataType< ::aruco_service::GenerateArUcoTags >::value();
  }
  static const char* value(const ::aruco_service::GenerateArUcoTagsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARUCO_SERVICE_MESSAGE_GENERATEARUCOTAGS_H
